package net.povstalec.sgjourney.common.config;

import net.neoforged.neoforge.common.ModConfigSpec;

public class CommonTechConfig
{
	public static ModConfigSpec.BooleanValue fusion_core_infinite_energy;
	public static ModConfigSpec.LongValue fusion_core_energy_from_fuel;
	public static ModConfigSpec.IntValue fusion_core_fuel_capacity;
	
	public static ModConfigSpec.BooleanValue disable_kara_kesh_requirements;
	public static ModConfigSpec.IntValue personal_shield_capacity;
	
	public static ModConfigSpec.IntValue vial_capacity;
	public static ModConfigSpec.LongValue energy_from_liquid_naquadah;
	public static ModConfigSpec.LongValue energy_from_heavy_liquid_naquadah;
	public static ModConfigSpec.LongValue naquadah_power_cell_buffer_capacity;
	public static ModConfigSpec.LongValue naquadah_power_cell_max_transfer;
	
	public static ModConfigSpec.LongValue naquadah_liquidizer_energy_capacity;
	public static ModConfigSpec.LongValue naquadah_liquidizer_max_energy_receive;
	public static ModConfigSpec.LongValue naquadah_liquidizer_energy_per_tick;
	public static ModConfigSpec.IntValue naquadah_liquidizer_fluid_input_capacity;
	public static ModConfigSpec.IntValue naquadah_liquidizer_fluid_output_capacity;
	public static ModConfigSpec.IntValue naquadah_liquidizer_max_fluid_receive;
	public static ModConfigSpec.IntValue naquadah_liquidizer_max_fluid_extract;
	
	public static ModConfigSpec.LongValue heavy_naquadah_liquidizer_energy_capacity;
	public static ModConfigSpec.LongValue heavy_naquadah_liquidizer_max_energy_receive;
	public static ModConfigSpec.LongValue heavy_naquadah_liquidizer_energy_per_tick;
	public static ModConfigSpec.IntValue heavy_naquadah_liquidizer_fluid_input_capacity;
	public static ModConfigSpec.IntValue heavy_naquadah_liquidizer_fluid_output_capacity;
	public static ModConfigSpec.IntValue heavy_naquadah_liquidizer_max_fluid_receive;
	public static ModConfigSpec.IntValue heavy_naquadah_liquidizer_max_fluid_extract;
	
	public static ModConfigSpec.LongValue crystallizer_energy_capacity;
	public static ModConfigSpec.LongValue crystallizer_max_energy_receive;
	public static ModConfigSpec.LongValue crystallizer_energy_per_tick;
	public static ModConfigSpec.IntValue crystallizer_fluid_input_capacity;
	public static ModConfigSpec.IntValue crystallizer_max_fluid_receive;
	
	public static ModConfigSpec.LongValue advanced_crystallizer_energy_capacity;
	public static ModConfigSpec.LongValue advanced_crystallizer_max_energy_receive;
	public static ModConfigSpec.LongValue advanced_crystallizer_energy_per_tick;
	public static ModConfigSpec.IntValue advanced_crystallizer_fluid_input_capacity;
	public static ModConfigSpec.IntValue advanced_crystallizer_max_fluid_receive;
	
	public static ModConfigSpec.LongValue small_naquadah_battery_capacity;
	public static ModConfigSpec.LongValue small_naquadah_battery_max_transfer;
	public static ModConfigSpec.LongValue large_naquadah_battery_capacity;
	public static ModConfigSpec.LongValue large_naquadah_battery_max_transfer;
	
	public static void init(ModConfigSpec.Builder server)
	{
		// Fusion Core
		
		fusion_core_infinite_energy = server
				.comment("If true, Fusion Core will produce an endless amount of energy and won't require any fuel")
				.define("server.fusion_core_infinite_energy", false);
		
		fusion_core_energy_from_fuel = server
				.comment("The amount of energy generated by Fusion Core from one unit of fuel")
				.defineInRange("server.fusion_core_energy_from_fuel", 100000, 1L, Long.MAX_VALUE);
		
		fusion_core_fuel_capacity = server
				.comment("The fuel capacity of a Fusion Core")
				.defineInRange("server.fusion_core_fuel_capacity", 65536, 1, Integer.MAX_VALUE);
		
		
		
		disable_kara_kesh_requirements = server
				.comment("If true Kara Kesh won't require its user to have Naquadah in their bloodstream")
				.define("server.disable_kara_kesh_requirements", false);
		
		personal_shield_capacity = server
				.comment("The amount of Heavy Liquid Naquadah a Personal Shield can hold")
				.defineInRange("server.personal_shield_capacity", 300, 1, Integer.MAX_VALUE);
		
		// Vial and Naquadah Power Cell
		
		vial_capacity = server
				.comment("The amount of Liquid Naquadah or Heavy Liquid Naquadah a Vial can hold")
				.defineInRange("server.vial_capacity", 250, 1, Integer.MAX_VALUE);
		
		energy_from_liquid_naquadah = server
				.comment("The amount of energy generated from one unit of Liquid Naquadah")
				.defineInRange("server.energy_from_liquid_naquadah", 10000L, 1, Long.MAX_VALUE);
		
		energy_from_heavy_liquid_naquadah = server
				.comment("The amount of energy generated from one unit of Heavy Liquid Naquadah")
				.defineInRange("server.energy_from_heavy_liquid_naquadah", 50000L, 1, Long.MAX_VALUE);
		
		naquadah_power_cell_buffer_capacity = server
				.comment("The amount of energy the Naquadah Power Cell's Energy Buffer can hold")
				.defineInRange("server.naquadah_power_cell_buffer_capacity", 50000L, 1, Long.MAX_VALUE);
		
		naquadah_power_cell_max_transfer = server
				.comment("The amount of energy the Naquadah Power Cell's Energy Buffer can transfer out at once")
				.defineInRange("server.naquadah_power_cell_max_transfer", 200000L, 1, Long.MAX_VALUE);
		
		// Liquidizers
		
		naquadah_liquidizer_energy_capacity = server
				.comment("The maximum amount of energy the Naquadah Liquidizer can hold")
				.defineInRange("server.naquadah_liquidizer_energy_capacity", 1000000L, 1L, Long.MAX_VALUE);
		
		naquadah_liquidizer_max_energy_receive = server
				.comment("The maximum amount of energy the Naquadah Liquidizer can receive in one tick")
				.defineInRange("server.naquadah_liquidizer_max_energy_receive", 100000L, 1L, Long.MAX_VALUE);
		
		naquadah_liquidizer_energy_per_tick = server
				.comment("The amount of energy the Naquadah Liquidizer depletes per tick when active")
				.defineInRange("server.naquadah_liquidizer_energy_per_tick", 1000L, 0L, Long.MAX_VALUE);
		
		naquadah_liquidizer_fluid_input_capacity = server
				.comment("The maximum amount of fluid the input tank of the Naquadah Liquidizer can hold")
				.defineInRange("server.naquadah_liquidizer_fluid_input_capacity", 4000, 1, Integer.MAX_VALUE);
		
		naquadah_liquidizer_fluid_output_capacity = server
				.comment("The maximum amount of fluid the output tank of the Naquadah Liquidizer can hold")
				.defineInRange("server.naquadah_liquidizer_fluid_output_capacity", 4000, 1, Integer.MAX_VALUE);
		
		naquadah_liquidizer_max_fluid_receive = server
				.comment("The maximum amount of fluid the Naquadah Liquidizer can receive in one tick")
				.defineInRange("server.naquadah_liquidizer_max_fluid_receive", 1000, 1, Integer.MAX_VALUE);
		
		naquadah_liquidizer_max_fluid_extract = server
				.comment("The maximum amount of fluid that can be extracted from the Naquadah Liquidizer in one tick")
				.defineInRange("server.naquadah_liquidizer_max_fluid_extract", 1000, 1, Integer.MAX_VALUE);
		
		
		
		heavy_naquadah_liquidizer_energy_capacity = server
				.comment("The maximum amount of energy the Heavy Naquadah Liquidizer can hold")
				.defineInRange("server.heavy_naquadah_liquidizer_energy_capacity", 1000000L, 1L, Long.MAX_VALUE);
		
		heavy_naquadah_liquidizer_max_energy_receive = server
				.comment("The maximum amount of energy the Heavy Naquadah Liquidizer can receive in one tick")
				.defineInRange("server.heavy_naquadah_liquidizer_max_energy_receive", 100000L, 1L, Long.MAX_VALUE);
		
		heavy_naquadah_liquidizer_energy_per_tick = server
				.comment("The amount of energy the Heavy Naquadah Liquidizer depletes per tick when active")
				.defineInRange("server.heavy_naquadah_liquidizer_energy_per_tick", 1000L, 0L, Long.MAX_VALUE);
		
		heavy_naquadah_liquidizer_fluid_input_capacity = server
				.comment("The maximum amount of fluid the input tank of the Heavy Naquadah Liquidizer can hold")
				.defineInRange("server.heavy_naquadah_liquidizer_fluid_input_capacity", 4000, 1, Integer.MAX_VALUE);
		
		heavy_naquadah_liquidizer_fluid_output_capacity = server
				.comment("The maximum amount of fluid the output tank of the Heavy Naquadah Liquidizer can hold")
				.defineInRange("server.heavy_naquadah_liquidizer_fluid_output_capacity", 4000, 1, Integer.MAX_VALUE);
		
		heavy_naquadah_liquidizer_max_fluid_receive = server
				.comment("The maximum amount of fluid the Heavy Naquadah Liquidizer can receive in one tick")
				.defineInRange("server.heavy_naquadah_liquidizer_max_fluid_receive", 1000, 1, Integer.MAX_VALUE);
		
		heavy_naquadah_liquidizer_max_fluid_extract = server
				.comment("The maximum amount of fluid that can be extracted from the Heavy Naquadah Liquidizer in one tick")
				.defineInRange("server.heavy_naquadah_liquidizer_max_fluid_extract", 1000, 1, Integer.MAX_VALUE);
		
		// Crystallizers
		
		crystallizer_energy_capacity = server
				.comment("The maximum amount of energy the Crystallizer can hold")
				.defineInRange("server.crystallizer_energy_capacity", 1000000L, 1L, Long.MAX_VALUE);
		
		crystallizer_max_energy_receive = server
				.comment("The maximum amount of energy the Crystallizer can receive in one tick")
				.defineInRange("server.crystallizer_max_energy_receive", 100000L, 1L, Long.MAX_VALUE);
		
		crystallizer_energy_per_tick = server
				.comment("The amount of energy the Crystallizer depletes per tick when active")
				.defineInRange("server.crystallizer_energy_per_tick", 1000L, 0L, Long.MAX_VALUE);
		
		crystallizer_fluid_input_capacity = server
				.comment("The maximum amount of fluid the input tank of the Crystallizer can hold")
				.defineInRange("server.crystallizer_fluid_input_capacity", 4000, 1, Integer.MAX_VALUE);
		
		crystallizer_max_fluid_receive = server
				.comment("The maximum amount of fluid the Crystallizer can receive in one tick")
				.defineInRange("server.crystallizer_max_fluid_receive", 1000, 1, Integer.MAX_VALUE);
		
		
		
		advanced_crystallizer_energy_capacity = server
				.comment("The maximum amount of energy the Advanced Crystallizer can hold")
				.defineInRange("server.advanced_crystallizer_energy_capacity", 1000000L, 1L, Long.MAX_VALUE);
		
		advanced_crystallizer_max_energy_receive = server
				.comment("The maximum amount of energy the Advanced Crystallizer can receive in one tick")
				.defineInRange("server.advanced_crystallizer_max_energy_receive", 100000L, 1L, Long.MAX_VALUE);
		
		advanced_crystallizer_energy_per_tick = server
				.comment("The amount of energy the Advanced Crystallizer depletes per tick when active")
				.defineInRange("server.advanced_crystallizer_energy_per_tick", 1000L, 0L, Long.MAX_VALUE);
		
		advanced_crystallizer_fluid_input_capacity = server
				.comment("The maximum amount of fluid the input tank of the Advanced Crystallizer can hold")
				.defineInRange("server.advanced_crystallizer_fluid_input_capacity", 4000, 1, Integer.MAX_VALUE);
		
		advanced_crystallizer_max_fluid_receive = server
				.comment("The maximum amount of fluid the Advanced Crystallizer can receive in one tick")
				.defineInRange("server.advanced_crystallizer_max_fluid_receive", 1000, 1, Integer.MAX_VALUE);
		
		// Naquadah Batteries
		
		small_naquadah_battery_capacity = server
				.comment("The amount of energy a Small Naquadah Battery can hold")
				.defineInRange("server.small_naquadah_battery_capacity", 5000000L, 1L, Long.MAX_VALUE);
		
		small_naquadah_battery_max_transfer = server
				.comment("The amount of energy a Small Naquadah Battery can transfer in one tick")
				.defineInRange("server.small_naquadah_battery_max_transfer", 10000L, 1L, Long.MAX_VALUE);
		
		large_naquadah_battery_capacity = server
				.comment("The amount of energy a Large Naquadah Battery can hold")
				.defineInRange("server.large_naquadah_battery_capacity", 1000000000L, 1L, Long.MAX_VALUE);
		
		large_naquadah_battery_max_transfer = server
				.comment("The amount of energy a Large Naquadah Battery can transfer in one tick")
				.defineInRange("server.large_naquadah_battery_max_transfer", 100000L, 1L, Long.MAX_VALUE);
	}
}
